pipeline{
     agent any
     
     stages{
      stage ("Check stage"){
      steps{
          sh 'mvn -- version'
      }
      
      }
      
      stage ("Compile stage'){
      steps{
      sh 'mvn clean compile'
      }
      
      }
       stage ('test stage'){
       steps{
       sh 'mvn test'
       }
       
       }
       }
       
       